public class DatetimeMethodsDemo{
    public void calculateAgeInMonths(){
        system.debug('we will calculate our age in months');
        Date todayDate= Date.today();
        Date duduBirthDate= Date.newInstance(1991, 3, 9);

        integer duAgeInMonhts = duduBirthDate.monthsBetween(todayDate);
        system.debug ( 'Dudu age in months '+ duAgeInMonhts);
    }

    public void calculateAgeInDays(){
        Date todayDate= Date.today();
        Date duduBirthdate= Date.newInstance(1991, 3, 10);
        Integer duAgeInDays= duduBirthdate.daysBetween(todayDate);
        system.debug('Dudu age in days '+ duAgeInDays);
    }

    public void printSubscriptionEndDate(){
        Date startDate1= Date.today();

        Date endDate1= startDate1.addDays(1000);
        system.debug('Subscription ends on '+ endDate1);

        //today is end date of 1000days of subscription. Get startDate
       date endDate2 = date.today();
        //use addDays method to add days
        date startDate2 = endDate2.addDays(-1000);
        system.debug('Subscription start date2 is ' + startDate2);
       //get YEAR component from date
        integer startYear = startDate2.year();
        system.debug('start year of subscription was ' + startYear);
        integer startMonth = startDate2.month();
        system.debug('month year of subscription was ' + startMonth);
    }

    public void printOfferEndDatetime(){
        //today -> date
        //now   -> datetime
        datetime offerStartDT = datetime.now();
        //print offer end datetime, if offer is for 51 hours
        datetime offerEndDT = offerStartDT.addHours(51);
        system.debug('offer end datetime is ' + offerEndDT);
    }

      
}