public class ReturnClassAssignment {
    public String returnStringMethod(String name, String lastName) {
        String fullName= name+ lastName;
        return fullName;


    }
    public Integer  addition(Integer x, integer y){
        Integer z= x+y;
        return z;

    }

    public Integer  addition2(Integer f, Integer g, Integer h, Integer i){
        Integer sumValue= f+g+h+i;
        return sumValue;

    }
}