ListDemo2.iterateListString99();





list<string> list9 = new list<string>{'yavuz', 'sultan', 'selim', 'fatih', 'sultan', 'mehmet'};
system.debug(listDemo2.add(list9));

ListDemo2.iterateListString1();

//creating new list and assigning some values
list<integer> l = new list<integer>{8, 9, 21, 15, 45,101, 121};
List<String> ls= new List<String>{'selam','hola','hi'};
integer sum1 = ListDemo2.add(l);
system.debug('final sum is ' + sum1);


